---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build_monitor_image
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: app/monitor/Dockerfile
    force_tag: true
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/dq-kube-monitor-dashboard
    tags:
    - latest
    - ${DRONE_COMMIT_SHA}
    - b${DRONE_BUILD_NUMBER}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    event:
    - push

- name: trivy_scan
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/trivyscanner:master
  commands:
  - trivy --version
  - trivy image --ignore-unfixed --exit-code 1 --no-progress quay.io/ukhomeofficedigital/dq-kube-monitor-dashboard:${DRONE_COMMIT_SHA}
  when:
    branch:
      exclude:
      - master
    event:
    - push

- name: deploy_to_notprod
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export ENV=$$ENV
  - export FMS_KEY=$$NOTPROD_FMS_KEY
  - export FMS_CERT=$$NOTPROD_FMS_CERT
  - export TAB_ADMIN_PWD=$$NOTPROD_TAB_ADMIN_PWD
  - export KUBE_TOKEN=$$NOTPROD_KUBE_TOKEN
  - export KUBE_SERVER=$$NOTPROD_KUBE_SERVER
  - export AWS_ACCESS_KEY_ID=$$NOTPROD_AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$$NOTPROD_AWS_SECRET_ACCESS_KEY
  - export AWS_DEFAULT_REGION=$$AWS_DEFAULT_REGION
  - export SLACK_URL=$$NOTPROD_SLACK_URL
  - kd --delete --file deployment.yml
  - "kd -f pvc.yml -f service.yml -f secrets.yml -f aws_secrets.yml \
      -f network-policy.yml -f deployment.yml  --timeout 5m0s"
  environment:
    AWS_DEFAULT_REGION:
      from_secret: AWS_DEFAULT_REGION
    ENV: notprod
    INSECURE_SKIP_TLS_VERIFY: true
    KUBE_NAMESPACE: dq-apps-notprod
    NOTPROD_AWS_ACCESS_KEY_ID:
      from_secret: NOTPROD_AWS_ACCESS_KEY_ID
    NOTPROD_AWS_SECRET_ACCESS_KEY:
      from_secret: NOTPROD_AWS_SECRET_ACCESS_KEY
    NOTPROD_FMS_CERT:
      from_secret: NOTPROD_FMS_CERT
    NOTPROD_FMS_KEY:
      from_secret: NOTPROD_FMS_KEY
    NOTPROD_KUBE_SERVER:
      from_secret: NOTPROD_KUBE_SERVER
    NOTPROD_KUBE_TOKEN:
      from_secret: NOTPROD_KUBE_TOKEN
    NOTPROD_TAB_ADMIN_PWD:
      from_secret: NOTPROD_TAB_ADMIN_PWD
    NOTPROD_SLACK_URL:
      from_secret: NOTPROD_SLACK_URL
    VOLUME_SIZE: 10Gi
  when:
    event:
    - push

- name: deploy_to_prod
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  # - export ENV=$$ENV
  - export FMS_KEY=$$PROD_FMS_KEY
  - export FMS_CERT=$$PROD_FMS_CERT
  - export TAB_ADMIN_PWD=$$PROD_TAB_ADMIN_PWD
  - export KUBE_TOKEN=$$PROD_KUBE_TOKEN
  - export KUBE_SERVER=$$PROD_KUBE_SERVER
  - export AWS_ACCESS_KEY_ID=$$PROD_AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$$PROD_AWS_SECRET_ACCESS_KEY
  - export AWS_DEFAULT_REGION=$$AWS_DEFAULT_REGION
  - export SLACK_URL=$$PROD_SLACK_URL
  - kd --delete --file deployment.yml
  - "kd -f pvc.yml -f service.yml -f secrets.yml -f aws_secrets.yml \
      -f network-policy.yml -f deployment.yml --timeout 5m0s"
  environment:
    AWS_DEFAULT_REGION:
      from_secret: AWS_DEFAULT_REGION
    ENV: prod
    INSECURE_SKIP_TLS_VERIFY: true
    KUBE_NAMESPACE: dq-apps
    PROD_AWS_ACCESS_KEY_ID:
      from_secret: PROD_AWS_ACCESS_KEY_ID
    PROD_AWS_SECRET_ACCESS_KEY:
      from_secret: PROD_AWS_SECRET_ACCESS_KEY
    PROD_FMS_CERT:
      from_secret: PROD_FMS_CERT
    PROD_FMS_KEY:
      from_secret: PROD_FMS_KEY
    PROD_KUBE_SERVER:
      from_secret: PROD_KUBE_SERVER
    PROD_KUBE_TOKEN:
      from_secret: PROD_KUBE_TOKEN
    PROD_SLACK_URL:
      from_secret: PROD_SLACK_URL
    PROD_TAB_ADMIN_PWD:
      from_secret: PROD_TAB_ADMIN_PWD
    VOLUME_SIZE: 10Gi
  when:
    branch:
    - master
    event:
    - promote
    target:
    - production

- name: delete_prod
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export KUBE_TOKEN=$$PROD_KUBE_TOKEN
  - export KUBE_SERVER=$$PROD_KUBE_SERVER
  - "kd --delete --file deployment.yml --file pvc.yml\n"
  environment:
    ENV: prod
    INSECURE_SKIP_TLS_VERIFY: true
    KUBE_NAMESPACE: dq-apps
    PROD_KUBE_SERVER:
      from_secret: PROD_KUBE_SERVER
    PROD_KUBE_TOKEN:
      from_secret: PROD_KUBE_TOKEN
    VOLUME_SIZE: 10Gi
  when:
    branch:
    - master
    event:
    - promote
    target:
    - delete

...
