

pipeline:
  build_monitor_image:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-kube-monitor-dashboard
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    context: app/monitor
    dockerfile: app/monitor/Dockerfile
    force_tag: true
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
      - b${DRONE_BUILD_NUMBER}
    when:
      event: push

  deploy_to_notprod:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - ENV=notprod
      - KUBE_NAMESPACE=dq-apps-notprod
      - INSECURE_SKIP_TLS_VERIFY=true
      - VOLUME_SIZE=10Gi
      - FMS_URL="http://fms.notprod.dq.homeoffice.gov.uk"
      - CRT_URL="http://crt-acp.notprod.dq.homeoffice.gov.uk"
      - GAIT-URL="http://gait.notprod.dq.homeoffice.gov.uk"
      - HOSTNAME=monitor.notprod.dq.homeoffice.gov.uk
      # - GF_AWS_NOTPROD_ACCESS_KEY_ID=${GF_AWS_NOTPROD_ACCESS_KEY_ID}
      # - GF_AWS_NOTPROD_SECRET_ACCESS_KEY=${GF_AWS_NOTPROD_SECRET_ACCESS_KEY}

    secrets:
      - NOTPROD_KUBE_TOKEN
      - NOTPROD_KUBE_SERVER
      # - NOTPROD_WHITELIST_RANGES

    commands:
      - export KUBE_TOKEN=$$NOTPROD_KUBE_TOKEN
      - export KUBE_SERVER=$$NOTPROD_KUBE_SERVER
      # - export WHITELIST_RANGES=$$NOTPROD_WHITELIST_RANGES
      - |
        kd --file pvc.yml --file service.yml --file network-policy.yml --file deployment.yml

    when:
      event: push

  # deploy_to_prod:
  #   image: quay.io/ukhomeofficedigital/kd
  #   environment:
  #     - ENV=prod
  #     - JIRA_VERSION=${JIRA_VERSION}
  #     - KUBE_NAMESPACE=dq-management
  #     - INSECURE_SKIP_TLS_VERIFY=true
  #     - JIRA_HOME_VOLUME_SIZE=25Gi
  #     - HOSTNAME=jira.dq.homeoffice.gov.uk
  #     - DATABASE_SECRET_NAME=dq-management-jira-rds-access
  #     - AWS_BUCKET_SECRET_NAME=s3-dq-management-jira-backup
  #     - DATABASE_SCHEMA_NAME=public
  #   commands:
  #     - export KUBE_TOKEN=$$PROD_KUBE_TOKEN
  #     - export KUBE_SERVER=$$PROD_KUBE_SERVER
  #     - export BUCKET_NAME=$$PROD_BUCKET_NAME
  #     - export ACCESS_KEY_ID=$$PROD_ACCESS_KEY_ID
  #     - export SECRET_ACCESS_KEY=$$PROD_SECRET_ACCESS_KEY
  #     - export SLACK_WEBHOOK=$$PROD_SLACK_WEBHOOK
  #     - kd -f network-policy.yml -f pvc.yml -f service.yml -f ingress.yml -f secrets.yml -f deployment.yml
  #   secrets:
  #     - PROD_KUBE_TOKEN
  #     - PROD_KUBE_SERVER
  #     - PROD_BUCKET_NAME
  #     - PROD_ACCESS_KEY_ID
  #     - PROD_SECRET_ACCESS_KEY
  #     - PROD_SLACK_WEBHOOK
  #   when:
  #     environment: production
  #     branch: master
  #     event: deployment
