---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dq-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dq-monitor
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: dq-monitor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/dq-monitor/prometheus"
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: monitor
        image: quay.io/ukhomeofficedigital/dq-kube-monitor-dashboard:{{ .DRONE_COMMIT_SHA }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            cpu: 2
            memory: 2.5Gi
          requests:
            cpu: 1.5
            memory: 2.5Gi
        env:
          - name: FMS_URL
            {{ if eq .ENV "notprod" }}value: 'http://fms.notprod.dq.homeoffice.gov.uk'{{ end }}
            {{ if eq .ENV "prod" }}value: 'http://fms.dq.homeoffice.gov.uk'{{ end }}
          - name: CRT_URL
            {{ if eq .ENV "notprod" }}value: 'http://crt-acp.notprod.dq.homeoffice.gov.uk'{{ end }}
            {{ if eq .ENV "prod" }}value: 'http://crt.prod.dq.homeoffice.gov.uk'{{ end }}
          - name: GAIT_URL
            {{ if eq .ENV "notprod" }}value: 'http://gait.notprod.dq.homeoffice.gov.uk'{{ end }}
            {{ if eq .ENV "prod" }}value: 'http://gait.dq.homeoffice.gov.uk'{{ end }}
          - name: TAB_URL
            value: 'http://127.0.0.1:5000'
          - name: DRT_JSN_GRP
            {{ if eq .ENV "notprod" }}value: 'drt-notprod-json-lambda'{{ end }}
            {{ if eq .ENV "prod" }}value: 'drt-prod-json-lambda'{{ end }}
          - name: DRT_ATH_GRP
            {{ if eq .ENV "notprod" }}value: 'drt-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'drt-prod-lambda-athena'{{ end }}
          - name: DRT_RDS_GRP
            {{ if eq .ENV "notprod" }}value: 'drt-notprod-lambda-rds'{{ end }}
            {{ if eq .ENV "prod" }}value: 'drt-prod-lambda-rds'{{ end }}
        ports:
          - containerPort: 8000
        volumeMounts:
          - mountPath: /APP/share
            name: dq-monitor-storage
          - mountPath: /APP/fms-certs
            name: fms-cert-key
            readOnly: true

      - name: opensslsidekick
        image: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick:master
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
          - name: EXPOSED_PORT
            value: '5000'
          - name: HOST
            value: '10.3.0.11'
          - name: PORT
            value: '8081'
        ports:
          - containerPort: 5000
      volumes:
        - name: dq-monitor-storage
          persistentVolumeClaim:
            claimName: dq-monitor-storage
        - name: fms-cert-key
          secret:
            secretName: fms-cert-key
