---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dq-monitor
  annotations:
    environment: {{ .ENV }}
    {{ if eq .ENV "notprod" }}downscaler/uptime: Mon-Fri 07:00-18:00 Europe/London{{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dq-monitor
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: dq-monitor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .CONTAINER_PORT }}"
        prometheus.io/path: "/dq-monitor/prometheus"
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: monitor
        image: quay.io/ukhomeofficedigital/dq-kube-monitor-dashboard:{{ .DRONE_COMMIT_SHA }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            cpu: 2
            memory: 2.5Gi
          requests:
            cpu: 1.5
            memory: 2.5Gi
        env:
          - name: ENV
            value: {{ .ENV }}
          - name: FMS_URL
            {{ if eq .ENV "notprod" }}value: 'http://fms.notprod.dq.homeoffice.gov.uk'{{ end }}
            {{ if eq .ENV "prod" }}value: 'http://fms.dq.homeoffice.gov.uk'{{ end }}
          - name: CRT_URL
            {{ if eq .ENV "notprod" }}value: 'http://crt-acp.notprod.dq.homeoffice.gov.uk'{{ end }}
            {{ if eq .ENV "prod" }}value: 'http://crt.prod.dq.homeoffice.gov.uk'{{ end }}
          - name: GAIT_URL
            {{ if eq .ENV "notprod" }}value: 'http://gait.notprod.dq.homeoffice.gov.uk'{{ end }}
            {{ if eq .ENV "prod" }}value: 'http://gait.dq.homeoffice.gov.uk'{{ end }}
          - name: TAB_URL
            value: 'http://127.0.0.1:5000'
          - name: EXTTAB_URL
            {{ if eq .ENV "notprod" }}value: 'http://carrierportal.notprod.dq.homeoffice.gov.uk'{{ end }}
            {{ if eq .ENV "prod" }}value: 'http://carrierportal.dq.homeoffice.gov.uk'{{ end }}
          - name: TAB_API_VERSION
            value: '3.7'
          - name: DRT_JSN_GRP
            {{ if eq .ENV "notprod" }}value: 'drt-notprod-json-lambda'{{ end }}
            {{ if eq .ENV "prod" }}value: 'drt-prod-json-lambda'{{ end }}
          - name: DRT_ATH_GRP
            {{ if eq .ENV "notprod" }}value: 'drt-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'drt-prod-lambda-athena'{{ end }}
          - name: DRT_RDS_GRP
            {{ if eq .ENV "notprod" }}value: 'drt-notprod-lambda-rds'{{ end }}
            {{ if eq .ENV "prod" }}value: 'drt-prod-lambda-rds'{{ end }}
          - name: BF_API_PRS
            {{ if eq .ENV "notprod" }}value: 'api-kafka-input-notprod-lambda'{{ end }}
            {{ if eq .ENV "prod" }}value: 'api-kafka-input-prod-lambda'{{ end }}
          - name: BF_API_RAW
            {{ if eq .ENV "notprod" }}value: 'cdlz-notprod-lambda'{{ end }}
            {{ if eq .ENV "prod" }}value: 'cdlz-prod-lambda'{{ end }}
          - name: BF_SCH_CNS
            {{ if eq .ENV "notprod" }}value: 'consolidated-schedule-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'consolidated-schedule-prod-lambda-athena'{{ end }}
          - name: BF_SCH_ACL
            {{ if eq .ENV "notprod" }}value: 'acl-input-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'acl-input-prod-lambda-athena'{{ end }}
          - name: BF_SCH_FS
            {{ if eq .ENV "notprod" }}value: 'fs-input-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'fs-input-prod-lambda-athena'{{ end }}
          - name: BF_SCH_OAG
            {{ if eq .ENV "notprod" }}value: 'oag-transform-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'oag-transform-prod-lambda-athena'{{ end }}
          - name: BF_XRS_ATH
            {{ if eq .ENV "notprod" }}value: 'api-cross-record-scored-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'api-cross-record-scored-prod-lambda-athena'{{ end }}
          - name: BF_RLS_ATH
            {{ if eq .ENV "notprod" }}value: 'api-record-level-score-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'api-record-level-score-prod-lambda-athena'{{ end }}
          - name: BF_ASR_ATH
            {{ if eq .ENV "notprod" }}value: 'api-accuracy-scoring-notprod-lambda-scoring-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'api-accuracy-scoring-prod-lambda-scoring-athena'{{ end }}
          - name: BF_AS_ATH
            {{ if eq .ENV "notprod" }}value: 'api-accuracy-scoring-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'api-accuracy-scoring-prod-lambda-athena'{{ end }}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: dq-monitor-secrets
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: dq-monitor-secrets
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: dq-monitor-secrets
                key: AWS_DEFAULT_REGION
          - name: TAB_ADMIN_PWD
            valueFrom:
              secretKeyRef:
                name: dq-monitor-secrets
                key: TAB_ADMIN_PWD
          - name: SLACK_URL
            valueFrom:
              secretKeyRef:
                name: dq-monitor-secrets
                key: SLACK_URL
        ports:
          - containerPort: {{ .CONTAINER_PORT }}
        volumeMounts:
          - mountPath: /APP/share
            name: dq-monitor-storage
          - mountPath: /APP/auth-files
            name: auth-files
            readOnly: true
      - name: opensslsidekick-tab
        image: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick:{{ .HAPROXY_SIDEKICK_VERSION }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
          - name: EXPOSED_PORT
            value: '{{ .TAB_EXPOSE_PORT }}'
          - name: HOST
            value: '{{ .TAB_IP }}'
          - name: PORT
            value: '{{ .TAB_PORT }}'
        ports:
          - containerPort: {{ .TAB_EXPOSE_PORT }}
      - name: opensslsidekick-fms
        image: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick:{{ .HAPROXY_SIDEKICK_VERSION }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
          - name: EXPOSED_PORT
            value: '{{ .FMS_EXPOSE_PORT }}'
          - name: HOST
            value: '{{ .FMS_IP }}'
          - name: PORT
            value: '{{ .FMS_PORT }}'
        ports:
          - containerPort: {{ .FMS_EXPOSE_PORT }}
      - name: opensslsidekick-gait
        image: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick:{{ .HAPROXY_SIDEKICK_VERSION }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
          - name: EXPOSED_PORT
            value: '{{ .GAIT_EXPOSE_PORT }}'
          - name: HOST
            value: '{{ .GAIT_IP }}'
          - name: PORT
            value: '{{ .GAIT_PORT }}'
        ports:
          - containerPort: {{ .GAIT_EXPOSE_PORT }}
      - name: opensslsidekick-tab-rds
        image: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick:{{ .HAPROXY_SIDEKICK_VERSION }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
          - name: EXPOSED_PORT
            value: '{{ .TABRDS_EXPOSE_PORT }}'
          - name: HOST
            value: '{{ .TABRDS_IP }}'
          - name: PORT
            value: '{{ .TABRDS_PORT }}'
        ports:
          - containerPort: {{ .TABRDS_EXPOSE_PORT }}
      - name: opensslsidekick-exttab
        image: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick:{{ .HAPROXY_SIDEKICK_VERSION }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
          - name: EXPOSED_PORT
            value: '{{ .EXTTAB_EXPOSE_PORT }}'
          - name: HOST
            value: '{{ .EXTTAB_IP }}'
          - name: PORT
            value: '{{ .EXTTAB_PORT }}'
        ports:
          - containerPort: {{ .EXTTAB_EXPOSE_PORT }}
      volumes:
        - name: dq-monitor-storage
          persistentVolumeClaim:
            claimName: dq-monitor-storage
        - name: auth-files
          secret:
            secretName: auth-files
