---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dq-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dq-monitor
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: dq-monitor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/dq-monitor/prometheus"
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: monitor
        image: quay.io/ukhomeofficedigital/dq-kube-monitor-dashboard:{{ .DRONE_COMMIT_SHA }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            cpu: 2
            memory: 2.5Gi
          requests:
            cpu: 1.5
            memory: 2.5Gi
        env:
          - name: FMS_URL
            {{ if eq .ENV "notprod" }}value: 'http://fms.notprod.dq.homeoffice.gov.uk'{{ end }}
            {{ if eq .ENV "prod" }}value: 'http://fms.dq.homeoffice.gov.uk'{{ end }}
          - name: CRT_URL
            {{ if eq .ENV "notprod" }}value: 'http://crt-acp.notprod.dq.homeoffice.gov.uk'{{ end }}
            {{ if eq .ENV "prod" }}value: 'http://crt.prod.dq.homeoffice.gov.uk'{{ end }}
          - name: GAIT_URL
            {{ if eq .ENV "notprod" }}value: 'http://gait.notprod.dq.homeoffice.gov.uk'{{ end }}
            {{ if eq .ENV "prod" }}value: 'http://gait.dq.homeoffice.gov.uk'{{ end }}
          - name: TAB_URL
            value: 'http://127.0.0.1:5000'
          - name: TAB_API_VERSION
            value: '3.7'
          - name: DRT_JSN_GRP
            {{ if eq .ENV "notprod" }}value: 'drt-notprod-json-lambda'{{ end }}
            {{ if eq .ENV "prod" }}value: 'drt-prod-json-lambda'{{ end }}
          - name: DRT_ATH_GRP
            {{ if eq .ENV "notprod" }}value: 'drt-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'drt-prod-lambda-athena'{{ end }}
          - name: DRT_RDS_GRP
            {{ if eq .ENV "notprod" }}value: 'drt-notprod-lambda-rds'{{ end }}
            {{ if eq .ENV "prod" }}value: 'drt-prod-lambda-rds'{{ end }}
          - name: BF_API_PRS
            {{ if eq .ENV "notprod" }}value: 'api-kafka-input-notprod-lambda'{{ end }}
            {{ if eq .ENV "prod" }}value: 'api-kafka-input-prod-lambda'{{ end }}
          - name: BF_API_RAW
            {{ if eq .ENV "notprod" }}value: 'cdlz-notprod-lambda'{{ end }}
            {{ if eq .ENV "prod" }}value: 'cdlz-prod-lambda'{{ end }}
          - name: BF_SCH_CNS
            {{ if eq .ENV "notprod" }}value: 'consolidated-schedule-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'consolidated-schedule-prod-lambda-athena'{{ end }}
          - name: BF_SCH_ACL
            {{ if eq .ENV "notprod" }}value: 'acl-input-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'acl-input-prod-lambda-athena'{{ end }}
          - name: BF_SCH_FS
            {{ if eq .ENV "notprod" }}value: 'fs-input-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'fs-input-prod-lambda-athena'{{ end }}
          - name: BF_SCH_OAG
            {{ if eq .ENV "notprod" }}value: 'oag-transform-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'oag-transform-prod-lambda-athena'{{ end }}
          - name: BF_XRS_ATH
            {{ if eq .ENV "notprod" }}value: 'api-cross-record-scored-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'api-cross-record-scored-prod-lambda-athena'{{ end }}
          - name: BF_RLS_ATH
            {{ if eq .ENV "notprod" }}value: 'api-record-level-score-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'api-record-level-score-prod-lambda-athena'{{ end }}
          - name: BF_ASR_ATH
            {{ if eq .ENV "notprod" }}value: 'api-accuracy-scoring-notprod-lambda-scoring-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'api-accuracy-scoring-prod-lambda-scoring-athena'{{ end }}
          - name: BF_AS_ATH
            {{ if eq .ENV "notprod" }}value: 'api-accuracy-scoring-notprod-lambda-athena'{{ end }}
            {{ if eq .ENV "prod" }}value: 'api-accuracy-scoring-prod-lambda-athena'{{ end }}
          - name: SLACK_URL
            {{ if eq .ENV "notprod" }}value: 'notprod_slack'{{ end }}
            {{ if eq .ENV "prod" }}value: 'https://hooks.slack.com/services/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'{{ end }}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: dq-monitor-secrets
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: dq-monitor-secrets
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: dq-monitor-secrets
                key: AWS_DEFAULT_REGION
          - name: TAB_ADMIN_PWD
            valueFrom:
              secretKeyRef:
                name: dq-monitor-secrets
                key: TAB_ADMIN_PWD
        ports:
          - containerPort: 8000
        volumeMounts:
          - mountPath: /APP/share
            name: dq-monitor-storage
          - mountPath: /APP/auth-files
            name: auth-files
            readOnly: true
      - name: opensslsidekick-tab
        image: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick:master
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
          - name: EXPOSED_PORT
            value: '5000'
          - name: HOST
            value: '10.3.0.12'
          - name: PORT
            value: '8081'
        ports:
          - containerPort: 5000
      - name: opensslsidekick-fms
        image: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick:master
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
          - name: EXPOSED_PORT
            value: '5001'
          - name: HOST
            value: '10.3.0.11'
          - name: PORT
            value: '5431'
        ports:
          - containerPort: 5001
      - name: opensslsidekick-gait
        image: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick:master
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
          - name: EXPOSED_PORT
            value: '5002'
          - name: HOST
            value: '10.3.0.11'
          - name: PORT
            value: '8087'
        ports:
          - containerPort: 5002
      - name: opensslsidekick-tab-rds
        image: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick:master
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
          - name: EXPOSED_PORT
            value: '5003'
          - name: HOST
            value: '10.3.0.11'
          - name: PORT
            value: '8084'
        ports:
          - containerPort: 5003
      volumes:
        - name: dq-monitor-storage
          persistentVolumeClaim:
            claimName: dq-monitor-storage
        - name: auth-files
          secret:
            secretName: auth-files
