apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dq-monitor
spec:
  podSelector:
    matchLabels:
      name: dq-monitor
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-external
    ports:
    - protocol: TCP
      port: 8000
