---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: dq-monitor
  name: dq-monitor
spec:
  ports:
  - name: prometheus-web
    port: 8000
    targetPort: 8000
  selector:
    name: dq-monitor
